### ISSUE TITLE
Refactor to closures

### ISSUE THREAD

**Issue by LuisBoto** [MasterCloudApps-Projects/patterned-nodeJS#5]
Refactor all js files to the new closure style

**Comment by lmorente** [comment]
When refactoring the code to clousures, we have found a problem with the decorator of the pawn (For the rest of the pieces it has been eliminated). By not making use of this, we cannot use the existing implementation and since it poses an inheritance problem it rejects the doAfterMovement() of the moveRules. 

The solution that we see before both things, is that the doAfterMovement() is a private method of the pawn that checks it after each movement, this would suppose a cycle between the getPawnMoveRule() and Piece().

**Comment by lmorente** [comment]
Refactor do in brach feature/piece_clousures -> Pending to resolve cpu player movement error to merge develop

**Comment by lmorente** [comment]
**Important: Define style guide for Enums**
There are 3 listed in the code: GameStatusEnum, PieceTypeEnum, PieceNameEnum. It would be important to define a coding style standard for them.
- File name (currently <name>Enum.js)
- name (currently UpperCamelCase)
- Doubt: Should enum functions be exported outside the enum?

![image](https://user-images.githubusercontent.com/85077458/193458720-e1d3b4a1-e3a9-42ee-9bb9-91a7cddd4771.png)

**Important: Define style guide for Class**
- do we continue with lowerCameCase in clousures?

**Comment by LuisBoto** [comment]
PieceTypeEnum and PieceNameEnum are now correctly coded as enums. GameStatusEnum isn't as important as there's 0 functionality tied to it right now, it's basically kept on a variable but there's nothing being done with its value. Refactor it to your liking.

> Important: Define style guide for Class
> 
>     * do we continue with lowerCameCase in clousures?

I thought UpperCamelCase would be less concerning standard-wise, however that seems to be debated:

https://stackoverflow.com/questions/7273316/what-is-the-javascript-filename-naming-convention

Given this i am not so sure how to proceed so i let the lowercase filenames be for now.
